package gps1920.g31.request_lib.events_information;

public enum EnumActionResult
{
    CONNECTION_ERROR("CONNECTION_ERROR"),

    LOGIN_SUCCESSFULL("LOGIN_SUCCESSFULL"),
    LOGIN_REFUSED("LOGIN_REFUSED"),

    REGISTER_SUCCESSFULL("REGISTER_SUCCESSFULL"),
    REGISTER_REFUSED("REGISTER_REFUSED"),

    NOT_ADMIN("NOT_ADMIN"),
    UNEXISTANT_EVENT("UNEXISTANT_EVENT"),

    INVALID_DATA("INVALID_DATA"),
    EVENT_ALREADY_EXISTS("EVENT_ALREADY_EXISTS"),
    EVENT_CREATION_SUCCESSFULL("EVENT_CREATION_SUCCESSFULL"),
    EDITION_SUCCESSFULL("EDITION_SUCCESSFULL"),
    EVENT_IS_PUBLISHED("EVENT_IS_PUBLISHED"),
    DELETED_SUCCESSFULLY("DELETED_SUCCESSFULLY"),

    UNEXISTANT_USER("UNEXISTANT_USER"),
    USER_EXISTS("USER_EXISTS"),
    USER_ALREADY_LOGGED_IN("USER_ALREADY_LOGGED_IN"),
    UNVALID_PASSWORD("UNVALID_PASSWORD");

    private String value;

    private EnumActionResult(String value)
    {
        this.value = value;
    }

    public String getValue()
    {
        return value;
    }
}